apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: soulbrowser-agent-alerts
  labels:
    app: soulbrowser-agent
spec:
  groups:
    - name: agent-health
      rules:
        - alert: SoulbrowserPermissionPromptFlood
          expr: rate(soul_agent_permission_prompt_total[5m]) > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High rate of permission prompts"
            description: "{{ $value }} prompts per second over the last 5m. Check watchdog/self-heal logs."
        - alert: SoulbrowserJudgeRejections
          expr: increase(soul_agent_judge_rejection_total[15m]) > 0
          labels:
            severity: critical
          annotations:
            summary: "Judge rejected structured outputs"
            description: "At least one plan failed QA in the last 15m. Inspect structured outputs."
        - alert: SoulbrowserParserFailures
          expr: increase(soul_agent_parser_failures_total[15m]) > 0
          labels:
            severity: warning
          annotations:
            summary: "Parser validation failures"
            description: "Structured parser validation failed. Investigate schema changes."
        - alert: SoulbrowserFallbackSpike
          expr: rate(soul_agent_fallback_to_baidu_total[5m]) > 3
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Search fallback triggered frequently"
            description: "LLM switched to Baidu fallback multiple times."
